#include<ESP8266WiFi.h>
#include<BlynkSimpleEsp8266.h>

char auth[] = "*****************"; //Enter the aoth code generated by Blynk App.

char ssid[] ="POCO PHONE"; //Enter your SSID name 
char pass[] ="Prince@61299"; //Enter your SSID passwaord
void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
Blynk.begin(mcq,ssid,pass);
}

void loop() {
  // put your main code here, to run repeatedly:
Blynk.run();
}